services:
  - type: web
    name: colab-keeper
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app_simple.py
    envVars:
      - key: COLAB_URL
        value: https://colab.research.google.com/drive/1jckV8xUJSmLhhol6wZwVJzpybsimiRw1
      - key: PORT
        value: 10000
    plan: free
    healthCheckPath: /status
