services:
  - type: web
    name: colab-virtual-browser
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: COLAB_URL
        value: https://colab.research.google.com/drive/1jckV8xUJSmLhhol6wZwVJzpybsimiRw1
      - key: BROWSERLESS_TOKEN
        sync: false  # You'll set this manually
      - key: PORT
        value: 10000
    plan: free
    healthCheckPath: /keep_alive
